Improve3

diff --git a/.github/workflows/StringUpdate.yml b/.github/workflows/StringUpdate.yml
--- a/.github/workflows/StringUpdate.yml
+++ b/.github/workflows/StringUpdate.yml
@@ -30,7 +30,7 @@ jobs:
           BOX_SUBJECT_ID: ${{ secrets.BOX_SUBJECT_ID }}
         run: |
           access_token=$(
-            curl -s -X POST \
+            curl --fail -s -X POST \
             -H "Content-Type:application/x-www-form-urlencoded" \
             -d "grant_type=${GRANT_TYPE}" \
             -d "client_id=${CLIENT_ID}" \
@@ -40,6 +40,12 @@ jobs:
             'https://api.box.com/oauth2/token' | \
             jq -r ".access_token"
           )
+          
+          if [ $? -ne 0 ] || [ -z "$access_token" ] || [ "$access_token" == "null" ]; then
+            echo "::error::Failed to retrieve access token correctly."
+            exit 1
+          fi
+          
           echo "::add-mask::${access_token}"
           echo "access_token=${access_token}" >> $GITHUB_OUTPUT  
 
@@ -54,6 +60,12 @@ jobs:
             "https://api.box.com/2.0/folders/${BOX_STRING_ROOT_DIRECTORY_ID}/items?limit=1&sort=date&direction=DESC" | \
             jq -r ".entries[0].id"
           )
+          
+          if [ $? -ne 0 ] || [ -z "$target_directory_id" ] || [ "$target_directory_id" == "null" ]; then
+            echo "::error::Failed to retrieve target_directory_id correctly."
+            exit 1
+          fi
+          
           echo "::add-mask::${target_directory_id}"
           echo "target_directory_id=${target_directory_id}" >> $GITHUB_OUTPUT
 
